# Generated by Django 5.2.7 on 2025-10-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
