# Generated by Django 5.2.7 on 2025-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_contactform_age_alter_contactform_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.TextField(default='No note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, default='No note', null=True),
        ),
    ]
