# Generated by Django 5.2.7 on 2025-10-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_contact_note_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('feature_button', models.CharField(max_length=50)),
            ],
        ),
    ]
