# Generated by Django 5.2.7 on 2025-10-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discliamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important_disclaimer', models.TextField()),
                ('footer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('steps', models.CharField(max_length=200)),
                ('step_discription', models.TextField()),
            ],
        ),
    ]
