# Generated by Django 5.2.7 on 2025-10-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_discliamer_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='content',
            field=models.TextField(default='no content yet'),
        ),
    ]
